server:
  port: 8080

spring:

  datasource:
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    root: INFO
    ru.noleg.bankcards: DEBUG
  file:
    name: logs/bankcards.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  expiration: ${TOKEN_EXPIRATION}

app:
  admin:
    password: ${DEFAULT_ADMIN_PASSWORD}
  user:
    password: ${DEFAULT_USER_PASSWORD}
  aes:
    secret: ${AES_KEY}
