name: CI/CD Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Сборка и тесты
      - name: Build with Maven
        run: mvn -B clean package

      # 4. Сохраняем JAR как артефакт (чтобы можно было скачать из GitHub Actions)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar